server:
  port: 8080

logging.level:
  root: INFO

spring:
  profiles:
    active: default


  #to limit the input size for images
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB



  datasource:
    #JDBC Connections
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbnew
    username: root
    password: abhisql

  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc.time_zone: UTC
    hibernate:
      ddl-auto: update
